version: '3.4'

services:

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
 
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sql-server-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1

  user.api:
    image: ${DOCKER_REGISTRY-}{docker_hub_id}}/userservice
    container_name: userservice
    build:
      context: .
      dockerfile:  Services/Applicant/Applicant.API/Dockerfile
    depends_on:
     - db
  
  question.api:
    image: ${DOCKER_REGISTRY-}{docker_hub_id}/questionservice
    container_name: questionservice
    build:
      context: .
      dockerfile: Services/Question/Question.API/Dockerfile
    depends_on:
     - db
  exam.api:
    image: ${DOCKER_REGISTRY-}{docker_hub_id}/examservice
    container_name: examservice
    build:
      context: .
      dockerfile: Services/Exam/Exam.API/Dockerfile
    depends_on:
     - db
  report.api:
    image: ${DOCKER_REGISTRY-}{docker_hub_id}/reportservice
    container_name: reportservice
    build:
     context: .
     dockerfile: Services/Report/Report.API/Dockerfile
    depends_on:
     - db

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}{docker_hub_id}/ocelotapigw
    build:
      context: .
      dockerfile: APIGateway/OcelotApi/Dockerfile

 
  
  