version: '3.4'

services:

  # rabbitmq:
  #   container_name: rabbitmq
  #   restart: always



  
  # report.api:
  #   container_name: reportservice
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://0.0.0.0:80
  #   ports:
  #     - "80"

 
  userservice:
    container_name: userservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "7010:80"
  question.api:
    container_name: questionservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "7020:80"
  exam.api:
    container_name: examservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "7030:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
        - userservice
        - question.api
        - exam.api
    ports:
    - "9000:80"