version: '3.4'

services:

  # rabbitmq:
  #   container_name: rabbitmq
  #   restart: always

  user.api:
    container_name: userservice
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_URLS: "http://+"
    ports:
      - "7000:80"
  
  # question.api:
  #   container_name: questionservice
  #   environment:
  #      ASPNETCORE_ENVIRONMENT: Staging
  #      ASPNETCORE_URLS: "http://+"
  #   ports:
  #     - "6002:80"
  exam.api:
    container_name: examservice
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_URLS: "http://+"
    ports:
      - "6012:80"

  # report.api:
  #   container_name: reportservice
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: "Staging"
  #     ASPNETCORE_URLS: "http://+"
  #   ports:
  #     - "6004:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_URLS: "http://+"
    depends_on:
        - user.api
        - exam.api
        # - question.api
        # - report.api
    ports:
    - "9000:80"